name: 16s-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _r-mutex=1.0.0
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.2
  - alsa-lib=1.1.5
  - appdirs=1.4.3
  - async-timeout=3.0.1
  - attrs=19.3.0
  - bcrypt=3.1.7
  - bioconductor-biobase=2.32.0
  - bioconductor-biocgenerics=0.18.0
  - bioconductor-biocparallel=1.4.3
  - bioconductor-biostrings=2.38.4
  - bioconductor-dada2=1.0.3
  - bioconductor-genomeinfodb=1.6.3
  - bioconductor-genomicalignments=1.6.3
  - bioconductor-genomicranges=1.22.4
  - bioconductor-iranges=2.4.8
  - bioconductor-rsamtools=1.22.0
  - bioconductor-s4vectors=0.8.11
  - bioconductor-shortread=1.28.0
  - bioconductor-summarizedexperiment=1.0.2
  - bioconductor-xvector=0.10.0
  - bioconductor-zlibbioc=1.16.0
  - blas=1.0
  - boto3=1.9.66
  - botocore=1.12.189
  - bz2file=0.98
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cachetools=3.1.1
  - cairo=1.16.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - configargparse=0.13.0
  - cryptography=2.8
  - cutadapt=1.18
  - datrie=0.8
  - decorator=4.4.1
  - docutils=0.15.2
  - dropbox=9.4.0
  - expat=2.2.5
  - fastq-multx=1.3.1
  - fastqc=0.11.8
  - fftw=3.3.8
  - filechunkio=1.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-forge=1
  - freetype=2.10.0
  - fribidi=1.0.5
  - ftputil=3.4
  - gdk-pixbuf=2.32.2
  - gettext=0.19.8.1
  - ghostscript=9.18
  - giflib=5.1.7
  - gitdb2=2.0.6
  - gitpython=3.0.5
  - glib=2.58.3
  - gobject-introspection=1.58.2
  - google-api-core=1.14.3
  - google-auth=1.8.2
  - google-cloud-core=1.1.0
  - google-cloud-storage=1.23.0
  - google-resumable-media=0.5.0
  - googleapis-common-protos=1.6.0
  - graphite2=1.3.13
  - graphviz=2.42.3
  - harfbuzz=2.4.0
  - icu=64.2
  - idna=2.8
  - imagemagick=7.0.9_7
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - jbig=2.1
  - jinja2=2.10.3
  - jmespath=0.9.4
  - jpeg=9c
  - jsonschema=3.2.0
  - lcms2=2.9
  - libcroco=0.6.13
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libpng=1.6.37
  - libprotobuf=3.11.1
  - librsvg=2.46.4
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - multidict=4.6.1
  - ncurses=6.1
  - networkx=2.4
  - numpy=1.17.4
  - numpy-base=1.17.4
  - openjdk=11.0.1
  - openjpeg=2.3.1
  - openssl=1.1.1d
  - pandas=0.25.3
  - pango=1.42.4
  - paramiko=2.7.1
  - pcre=8.43
  - perl=5.26.2
  - pigz=2.4
  - pip=19.3.1
  - pixman=0.38.0
  - pkg-config=0.29.2
  - prettytable=0.7.2
  - protobuf=3.11.1
  - psutil=5.6.7
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.19
  - pygments=2.5.2
  - pygraphviz=1.3
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pyrsistent=0.15.6
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.1
  - python-irodsclient=0.7.0
  - pytz=2019.3
  - pyyaml=5.2
  - r=3.2.2
  - r-base=3.2.2
  - r-bitops=1.0_6
  - r-boot=1.3_17
  - r-chron=2.3_47
  - r-class=7.3_14
  - r-cluster=2.0.3
  - r-codetools=0.2_14
  - r-colorspace=1.2_6
  - r-data.table=1.9.6
  - r-dichromat=2.0_0
  - r-digest=0.6.9
  - r-foreign=0.8_66
  - r-futile.logger=1.4.1
  - r-futile.options=1.0.0
  - r-ggplot2=2.1.0
  - r-gtable=0.1.2
  - r-hwriter=1.3.2
  - r-kernsmooth=2.23_15
  - r-labeling=0.3
  - r-lambda.r=1.1.7
  - r-lattice=0.20_33
  - r-latticeextra=0.6_26
  - r-magrittr=1.5
  - r-mass=7.3_45
  - r-matrix=1.2_2
  - r-mgcv=1.8_9
  - r-munsell=0.4.2
  - r-nlme=3.1_122
  - r-nnet=7.3_11
  - r-plyr=1.8.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=0.12.2
  - r-recommended=3.2.2
  - r-reshape2=1.4.1
  - r-rpart=4.1_10
  - r-scales=0.3.0
  - r-snow=0.4_1
  - r-spatial=7.3_11
  - r-stringi=1.0_1
  - r-stringr=1.0.0
  - r-survival=2.38_3
  - ratelimiter=1.2.0
  - readline=7.0
  - requests=2.22.0
  - rsa=4.0
  - s3transfer=0.1.13
  - setuptools=42.0.2
  - six=1.13.0
  - smmap2=2.0.5
  - snakemake=5.8.1
  - snakemake-minimal=5.8.1
  - sqlite=3.30.1
  - tk=8.6.8
  - urllib3=1.25.7
  - wheel=0.33.6
  - wrapt=1.11.2
  - xmlrunner=1.7.7
  - xopen=0.7.3
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.2.2
  - yarl=1.3.0
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.4

