name: 16s-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-dada2=1.14.0
  - bioconductor-decipher=2.14.0
  - cutadapt=2.7
  - fastq-multx=1.3.1
  - fastqc=0.11.8
  - pandas=0.25.3
  - python=3.7.6
  - r-base=3.6.2
  - snakemake=5.9.1
  - r-dplyr=0.8.3
  - jsonlite=1.6
