if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("dada2", version = "3.10")
BiocManager::install("DECIPHER")
install.packages("dplyr", "ggplot2", "Biostrings")